#---------------------------------------------------------------------
# GitHub Action Workflow to Deploy Flask App to AWS ElasticBeanstalk
#
# Version      Date        Info
# 1.0          2019        Initial Version
#
# Made by Denis Astahov ADV-IT Copyleft (c) 2019
#---------------------------------------------------------------------
name: CI-CD-Pipeline-to-AWS-ElasticBeastalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "elasticbeanstalk-eu-central-1-774305599718 "
  EB_APPLICATION_NAME       : "MyFlask"
  EB_ENVIRONMENT_NAME       : "MyFlask-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-central-1"

on: 
  push:
    branches: 
      - main

jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
    - name: Print Happy Message for CI finish
      run : echo "CI Pipeline part Finished successfully!"

    - name: Create ZIP deployment package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ *.git*

  my_cd_part:
    runs-on: ubuntu-latest
    needs: [my_ci_part]

    steps:     
    - name: Print Happy Message for CD finish
      run : echo "CD Pipeline part Finished successfully!"
